import type { Metadata } from 'next';
import { Boldonse, Inter } from 'next/font/google';
import './globals.scss';

const fontBoldonse = Boldonse({
  variable: '--font-boldonse',
  weight: '400',
});

const fontInter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${fontBoldonse.variable} ${fontInter.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
